In [3]:
import numpy as np

In [ ]:
np.array([2, 5, 7])

In [ ]:
arr = np.array([[2, 4, 9], [2, 4, 5]])

In [ ]:
type(arr)

In [11]:
range_val = np.arange(10000)

In [5]:
%timeit range_val** 2

The slowest run took 16.72 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.21 µs per loop


In [6]:
c = range(10000)
%timeit [i**2 for i in c]

100 loops, best of 3: 3.76 ms per loop


In [7]:
d = [i**2 for i in c]

In [9]:
%timeit lambda: c * d

10000000 loops, best of 3: 69.6 ns per loop


In [12]:
new_range = range_val * 2

In [13]:
%timeit range_val * new_range

The slowest run took 11.67 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 10.6 µs per loop


In [14]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.zeros((3, 2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [20]:
np.ones((2, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [26]:
np.full((3, 3), 4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [31]:
np.eye(4, dtype = np.int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [32]:
np.diag([2, 5, 8, 9])

array([[2, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [41]:
50 * np.random.random() + 2

16.106368781658958

In [47]:
np.random.random([3, 3])

array([[ 0.56835716,  0.61301471,  0.97449622],
       [ 0.80689193,  0.91914884,  0.06861218],
       [ 0.11221108,  0.09554789,  0.10625218]])